# Generated by Django 3.1.3 on 2023-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_numofbids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='numofbids',
            field=models.IntegerField(default=2),
        ),
    ]
