# Generated by Django 3.1.3 on 2023-01-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20230125_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='numofbids',
            field=models.IntegerField(default=1),
        ),
    ]
